Repository Fest-Friends/ff-frontend, pull requests merged in 2025-02, with the labels that each got.

#25 [Chore/24] 이미지 압축 & 자동 빌드 CI 추가
  .github/workflows/ci.yml
  src/app/(home)/layout/HomeLayout.tsx
Labels: ⚙️ Chore

#31 [Feat/30] Notice Page
  package-lock.json
  src/app/(afterLogin)/notification/_component/NoticeItem.tsx
  src/app/(afterLogin)/notification/_component/NoticeList.tsx
  src/app/(afterLogin)/notification/page.tsx
  src/app/_component/ui/SnackBar.tsx
  src/app/_component/ui/ToastBar.tsx
  src/app/_utils/getTitleFromSlug.ts
  tailwind.config.ts
  yarn.lock
Labels: ✨ feat, 🎨 Design

#34 [Feat/33] 푸터 퍼블리싱
  public/image/Github.png
  src/app/_component/ui/Footer.tsx
  src/app/layout.tsx
Labels: ✨ feat

#32 [Feat/22] 회원가입&로그인&세션방식으로 로그인 여부 확인
  package.json
  src/app/(afterLogin)/concert/_component/SearchConcert.tsx
  src/app/(beforeLogin)/login/_lib/fetchLogin.ts
  src/app/(beforeLogin)/login/_lib/loginSchema.ts
  src/app/(beforeLogin)/login/page.tsx
  src/app/(beforeLogin)/signUp/_lib/fetchSignUp.ts
  src/app/(beforeLogin)/signUp/_lib/signUpSchema.ts
  src/app/(beforeLogin)/signUp/page.tsx
  src/app/_component/ui/Input.tsx
  src/lib/fetchSession.ts
Labels: ✨ feat
